"""
ROSA OS — Patch proposal writer.
Writes improvement proposals to experimental/ directory.
NEVER auto-applies patches. Owner must explicitly confirm via API.
"""

from __future__ import annotations

import logging
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger("rosa.self_improvement.patcher")

EXPERIMENTAL_DIR = Path("experimental")


def _now_str() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d_%H-%M-%S")


class Patcher:
    """Writes and manages improvement proposals in experimental/."""

    def __init__(self, sandbox_dir: str = "experimental") -> None:
        self.sandbox = Path(sandbox_dir)
        self.sandbox.mkdir(parents=True, exist_ok=True)

    async def write_proposal(self, analysis: dict[str, Any]) -> str:
        """
        Write an improvement proposal to a Markdown file in experimental/.

        Returns the relative path of the created file.
        """
        proposal_id = str(uuid.uuid4())[:8]
        timestamp = _now_str()
        filename = f"{timestamp}_{proposal_id}.md"
        filepath = self.sandbox / filename

        proposals = analysis.get("proposals", [])
        root_causes = analysis.get("root_causes", [])

        lines = [
            f"# ROSA OS Improvement Proposal",
            f"",
            f"**ID:** `{proposal_id}`",
            f"**Generated:** {timestamp}",
            f"**Priority:** {analysis.get('priority', 'unknown')}",
            f"**Status:** PENDING (not applied)",
            f"",
            f"---",
            f"",
            f"## Summary",
            f"",
            analysis.get("summary", "No summary provided."),
            f"",
            f"## Root Causes",
            f"",
        ]

        for cause in root_causes:
            lines.append(f"- {cause}")

        lines += [
            f"",
            f"## Proposed Changes",
            f"",
        ]

        for i, proposal in enumerate(proposals, 1):
            risk = proposal.get("risk", "unknown")
            risk_emoji = {"low": "🟢", "medium": "🟡", "high": "🔴"}.get(risk, "⚪")
            lines += [
                f"### {i}. {proposal.get('title', 'Untitled')}",
                f"",
                f"**Target:** `{proposal.get('target_file', 'unknown')}`",
                f"**Risk:** {risk_emoji} {risk.upper()}",
                f"**Expected benefit:** {proposal.get('expected_benefit', 'N/A')}",
                f"",
                proposal.get("description", "No description."),
                f"",
            ]

        lines += [
            f"---",
            f"",
            f"## How to Apply",
            f"",
            f"**IMPORTANT:** Do NOT apply this manually. Use the API:",
            f"",
            f"```bash",
            f"# Review this file first, then:",
            f"curl -X POST 'http://localhost:8000/api/self-improve/{proposal_id}/apply?confirmed=true'",
            f"```",
            f"",
            f"*Generated by ROSA OS self-improvement cycle. All changes require explicit owner approval.*",
        ]

        filepath.write_text("\n".join(lines), encoding="utf-8")
        logger.info("Patcher: wrote proposal to %s", filepath)

        # Also save to memory DB
        try:
            from core.memory.store import get_store
            store = await get_store()
            await store.save_reflection(
                content=analysis.get("summary", ""),
                suggestions="\n".join(
                    f"- {p.get('title')}: {p.get('description')}"
                    for p in proposals
                ),
            )
        except Exception as exc:
            logger.warning("Patcher: failed to save reflection to DB: %s", exc)

        return str(filepath)

    async def list_proposals(self) -> list[dict[str, Any]]:
        """List all proposal files in experimental/."""
        proposals = []
        for f in sorted(self.sandbox.glob("*.md"), reverse=True):
            if f.name == ".gitkeep":
                continue
            try:
                content = f.read_text(encoding="utf-8")
                # Extract summary from first lines
                summary = ""
                in_summary = False
                for line in content.splitlines():
                    if line.startswith("## Summary"):
                        in_summary = True
                        continue
                    if in_summary and line.startswith("#"):
                        break
                    if in_summary and line.strip():
                        summary = line.strip()
                        break

                applied = "Status:** APPLIED" in content
                proposal_id = f.stem.split("_")[-1] if "_" in f.stem else f.stem
                created_at = f.stem[:19].replace("_", "T") if len(f.stem) >= 19 else "unknown"

                proposals.append({
                    "id": proposal_id,
                    "filename": f.name,
                    "summary": summary,
                    "created_at": created_at,
                    "applied": applied,
                })
            except Exception as exc:
                logger.warning("Patcher.list_proposals: error reading %s: %s", f.name, exc)

        return proposals

    async def apply_proposal(self, proposal_id: str) -> str | None:
        """
        Mark a proposal as applied.
        NOTE: This only marks the file — actual code changes must be done manually or via git.
        Returns a summary string, or None if not found.
        """
        for f in self.sandbox.glob("*.md"):
            if proposal_id in f.stem:
                content = f.read_text(encoding="utf-8")
                # Mark as applied
                content = content.replace(
                    "**Status:** PENDING (not applied)",
                    f"**Status:** APPLIED ({_now_str()})",
                )
                f.write_text(content, encoding="utf-8")
                logger.info("Patcher: marked proposal %s as applied", proposal_id)
                return f"Proposal {proposal_id} marked as applied. Check {f.name} for details."

        return None
